version: '3.3'
services:
    xteve:
        container_name: xteve
        network_mode: host
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
            - TZ=Europe/Berlin
        volumes:
            - '/opt/xteve/:/root/.xteve:rw'
            - '/opt/xteve/_config:/config:rw'
            - '/tmp/xteve/:/tmp/xteve:rw'
        deploy:
          resources:
            reservations:
              devices:
              - driver: nvidia
                device_ids: ['0', '3']
                capabilities: [compute,video,utility]
        build: .